TemplateRuntimeError
jinja2.exceptions.TemplateRuntimeError: No filter named 'nl2br' found.

Traceback (most recent call last)
File "C:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\v\Lib\site-packages\flask\app.py", line 1536, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\v\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\v\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\v\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\v\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\v\Lib\site-packages\flask\app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "c:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\PythonPureStack\routes.py", line 50, in user_details
return render_template(
       
File "C:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\v\Lib\site-packages\flask\templating.py", line 150, in render_template
return _render(app, template, context)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\v\Lib\site-packages\flask\templating.py", line 131, in _render
rv = template.render(context)
     ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\v\Lib\site-packages\jinja2\environment.py", line 1295, in render
self.environment.handle_exception()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\v\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
raise rewrite_traceback_stack(source=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "c:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\PythonPureStack\templates\user_details.html", line 1, in top-level template code
{% extends 'base.html' %}
File "c:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\PythonPureStack\templates\base.html", line 168, in top-level template code
{% block content %}{% endblock %}
File "c:\Users\pc\Desktop\PROJECTS\PERSONAL\FBI_face_recognition\PythonPureStack\templates\user_details.html", line 44, in block 'content'
{{ user.details|nl2br }}
jinja2.exceptions.TemplateRuntimeError: No filter named 'nl2br' found.
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.